# /var/lib/registry/docker/registry/v2/repositories
services:
  registry:
    image: factory-registry.com:1994/registry
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: factory-registry
    ports:
      - "1994:5000"
    volumes:
      - ${HOME}/registry-data:/var/lib/registry

volumes:
  registry-data: