version: '3.8'
services:
  db:
    image: newfwd-db/test
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: newfwd-db-test
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ${HOME}/postgres/postgres:/var/lib/postgresql/data
      - ./db-dumps/init.sql:/docker-entrypoint-initdb.d/init.sql
