FROM node:16-alpine
RUN apk add --no-cache git tzdata
ENV TZ=Asia/Ho_Chi_Minh
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile \
    && yarn cache clean
COPY . .
RUN yarn build
CMD ["yarn", "start"]
EXPOSE 3000
