FROM node:20-alpine as build

WORKDIR /app
COPY package*.json ./
RUN yarn install
COPY . .
# RUN yarn build

FROM nginx:stable-alpine
# COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]